[HW1] Eric860730's first attempt
yungyuc/nsdhw_21au pull request #10
Opened 2021-09-14 08:35 UTC by Eric860730

---
A good PR should include the following parts:

- [ ] A clear title
- [ ] A meaningful message for PR, as well as its commits
- [ ] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [ ] excluding any irrelevant files, such as binaries, text files, or dot files
- [ ] passing tests/CI

2021-09-14 08:59 UTC, yungyuc commented
@q40603 action hasn't run on this but I do not know why.  Could you take a look when you have time?

2021-09-14 11:50 UTC, Eric860730 commented
@yungyuc hello teacher, the github action seems to be triggered after i push again.

2021-09-14 12:02 UTC, q40603 commented
I just approved the action. Don't know why it didn't trigger before.

2021-09-14 12:05 UTC, Eric860730 commented
@q40603 thank you.

2021-09-14 12:26 UTC, yungyuc requested changes

2021-09-14 12:26 UTC, yungyuc commented on hw0/Eric860730/countline.py
> +#!/usr/bin/env python3
You do not need to turn in `hw0`.  And please remove unneeded file like this from your `hw1` submission.

2021-09-15 04:51 UTC, yungyuc approved these changes

2021-09-23 17:50 UTC, merged