[Proposal] anva-kn initial proposal
yungyuc/nsdhw_21au pull request #172
Opened 2021-10-20 10:52 UTC by anva-kn

---
A good PR should include the following parts:

- [x] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [ ] passing tests/CI

This PR is an initial proposal for the term project. Reference sections still need to be updated.

2021-10-20 22:53 UTC, yungyuc requested changes
Look like a clear plan.  It's better to resolve some of the points.

2021-10-20 22:53 UTC, yungyuc commented on proposal/anva-kn/README.rst
> +The module should be compatible with NumPy arrays
This is a good feature to have for processing a lot of data.

2021-10-20 22:53 UTC, yungyuc commented on proposal/anva-kn/README.rst
> +![ramanflow_flowchart.jpeg](../_resources/ramanflow_flowchart.jpeg)
The picture doesn't seem to be available.

2021-10-20 22:53 UTC, yungyuc commented on proposal/anva-kn/README.rst
> +However, an alternative means of installation would be git cloning the repo and installing using make.
Github is a better way to recruit collaborators.

2021-10-20 22:53 UTC, yungyuc commented on proposal/anva-kn/README.rst
> +        - FFT noise removal (TBD)
Do you plan to implement FFT yourself?

2021-10-20 22:53 UTC, yungyuc commented on proposal/anva-kn/README.rst
> +| 2   | Implement Preprocessing part 1 |
What are included in parts 1 and 2 in both preprocessing and processing?

2021-10-30 07:14 UTC, anva-kn commented
Dear professor. I've cleaned up the pr commit history. Thank you very much for taking your time to review it!

2021-10-30 13:24 UTC, yungyuc commented on proposal/anva-kn/README.rst
> +![ramanflow_flowchart.jpeg](../_resources/ramanflow_flowchart.jpeg)
Now it shows.

2021-10-30 13:24 UTC, yungyuc commented on proposal/anva-kn/README.rst
> +        - FFT noise removal (TBD)
Sounds good to me.

2021-10-30 13:26 UTC, yungyuc approved these changes

2021-10-30 13:26 UTC, yungyuc commented on proposal/anva-kn/README.rst
> +| 6     |   Binding to python, unittesting, debugging, writing basic documentation|
Unit tests are usually add along with the first working functions.  The later you add unit tests, the more time it takes you to finish a project.

You do not need to write tests before features as TDD suggested, though.  In my experience TDD is usually counter-productive.

2021-10-30 13:26 UTC, merged