wwweiwei hw1 attempt1
yungyuc/nsdhw_21au pull request #66
Opened 2021-09-17 15:11 UTC by wwweiwei

---
A good PR should include the following parts:

- [ ] A clear title
- [ ] A meaningful message for PR, as well as its commits
- [ ] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [ ] excluding any irrelevant files, such as binaries, text files, or dot files
- [ ] passing tests/CI

2021-09-17 23:30 UTC, yungyuc requested changes

2021-09-17 23:30 UTC, yungyuc commented on hw0/README.rst
> +  ../validate.sh | grep "GET POINT"
This is unrelated change and please do not include it in your PR.  You did not branch from `hw1`.

2021-09-17 23:31 UTC, yungyuc commented
@wwweiwei you have two PRs (the other #62).  Please close one and keep the other.  Both has issues.

2021-09-23 16:44 UTC, q40603 commented
did not branch from hw1 -1

2021-09-23 16:44 UTC, merged